# profile=pixel9 | pixel9a | pixel7 | pixel6a | pixel9proxl
profile=pixel9

# mode=auto  → Pixel AVD pe LIGHT (safe, BharatPe no crash)
# mode=light → sirf qemu hide, fingerprint change NAHI
# mode=full  → poora device spoof (generic emulator only)
mode=auto

# boot_apply=0 → props ONLY on Action tap
boot_apply=0
